name: flutter_medic
description: "Pharmaceutical Application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  pin_code_fields: ^8.0.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  mask_text_input_formatter: ^2.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  equatable: ^2.0.5

  oat_api:
    path: ./api/oat_api
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  freezed: ^2.5.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/sf_pro_display/sf_pro_display_regular.otf
          weight: 400
        - asset: fonts/sf_pro_display/sf_pro_display_medium.otf
          weight: 500
        - asset: fonts/sf_pro_display/sf_pro_display_semibold.otf
          weight: 600
        - asset: fonts/sf_pro_display/sf_pro_display_bold.otf
          weight: 700
